//Alan Himes
//ahimes1@cnm.edu
//TipsterFrame.java
package himesp1.javareview;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author ahimes1
 */
public class TipsterFrame extends javax.swing.JFrame {
    TipsterCalc calc;
    DecimalFormat df;
    
    /**
     * Creates new form TipsterFrame
     */
    public TipsterFrame() {
        initComponents();
        calc = new TipsterCalc();
        df = new DecimalFormat("#.##");
        
        //Anonymous inner class listener added for the reset button.
        jBtnReset.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                reset();
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblTitle = new javax.swing.JLabel();
        jLblAmount = new javax.swing.JLabel();
        jLblPeople = new javax.swing.JLabel();
        jLblTipScale = new javax.swing.JLabel();
        jLblTip = new javax.swing.JLabel();
        jLblTotalDiner = new javax.swing.JLabel();
        jLblTotal = new javax.swing.JLabel();
        jLblTipAmount = new javax.swing.JLabel();
        jTxfAmount = new javax.swing.JTextField();
        jTxfPeople = new javax.swing.JTextField();
        jTxfTipPercent = new javax.swing.JTextField();
        jSldRange = new javax.swing.JSlider();
        jTxfTip = new javax.swing.JTextField();
        jTxfTotal = new javax.swing.JTextField();
        jTxfTotalDiner = new javax.swing.JTextField();
        jBtnCalc = new javax.swing.JButton();
        jBtnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblTitle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblTitle.setText("Tipster Tip Calculator");
        jLblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLblAmount.setText("Amount of Bill:");

        jLblPeople.setText("Number of People:");

        jLblTipScale.setText("Tip Percentage:");

        jLblTip.setText("Tip %");

        jLblTotalDiner.setText("Total per Diner");

        jLblTotal.setText("Total Due with Tip:");

        jLblTipAmount.setText("Tip Amount:");

        jTxfAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxfAmountKeyReleased(evt);
            }
        });

        jTxfPeople.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxfPeopleKeyReleased(evt);
            }
        });

        jTxfTipPercent.setEditable(false);
        jTxfTipPercent.setText("15%");

        jSldRange.setMinimum(15);
        jSldRange.setMaximum(50);
        jSldRange.setValue(15);
        jSldRange.setMajorTickSpacing(5);
        jSldRange.setMinorTickSpacing(1);
        jSldRange.setPaintLabels(true);
        jSldRange.setPaintTicks(true);
        jSldRange.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSldRangeStateChanged(evt);
            }
        });

        jTxfTip.setEditable(false);

        jTxfTotal.setEditable(false);

        jTxfTotalDiner.setEditable(false);

        jBtnCalc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnCalc.setText("CALCULATE");
        jBtnCalc.setToolTipText("");
        jBtnCalc.setEnabled(false);
        jBtnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCalcActionPerformed(evt);
            }
        });

        jBtnReset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnReset.setText("RESET");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLblPeople)
                                    .addGap(138, 138, 138))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLblTip)
                                    .addGap(20, 20, 20)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblAmount)
                                .addGap(158, 158, 158)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxfPeople)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jTxfTipPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblTipAmount)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jBtnReset)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnCalc)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTxfTotalDiner, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(jTxfTotal)
                                .addComponent(jTxfTip)))))
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLblTotalDiner))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLblTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLblTipScale)
                        .addGap(18, 18, 18)
                        .addComponent(jSldRange, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblTitle)
                        .addGap(35, 35, 35)
                        .addComponent(jLblAmount))
                    .addComponent(jTxfAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLblPeople)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTxfPeople, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxfTipPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblTip))))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblTipScale)
                    .addComponent(jSldRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCalc)
                    .addComponent(jBtnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblTipAmount, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxfTip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLblTotal))
                    .addComponent(jTxfTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblTotalDiner)
                    .addComponent(jTxfTotalDiner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSldRangeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSldRangeStateChanged
        jTxfTipPercent.setText(jSldRange.getValue()+"%");
    }//GEN-LAST:event_jSldRangeStateChanged

    private void jTxfAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxfAmountKeyReleased
        fieldsCheck();
    }//GEN-LAST:event_jTxfAmountKeyReleased

    private void jTxfPeopleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxfPeopleKeyReleased
        fieldsCheck();
    }//GEN-LAST:event_jTxfPeopleKeyReleased

    private void jBtnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCalcActionPerformed
        try {
            if (Double.parseDouble(jTxfAmount.getText()) < 0.01 || 
                    Integer.parseInt(jTxfPeople.getText()) < 1) {
                displayMessage("Unable to calculate.\n"
                        + "Bill amount must be above zero dollars, "
                        + "number of people must be 1 or higher.");
                reset();
            }
            else {
                calc.setInputData(Double.parseDouble(jTxfAmount.getText()), 
                        Integer.parseInt(jTxfPeople.getText()),
                        (double)jSldRange.getValue());

                jTxfTip.setText("$"+df.format(calc.getTip()));
                jTxfTotal.setText("$"+df.format(calc.getTotal()));
                jTxfTotalDiner.setText("$"+df.format(calc.getTotalEach()));
            }
        } catch(NumberFormatException nfe) {
            displayMessage("Please input numbers!\n"
                    + "(Number of people must be a whole number.)");
            reset();
        } catch(Exception e) {
            displayMessage(e.toString());
            reset();
        }
        
    }//GEN-LAST:event_jBtnCalcActionPerformed

    private void fieldsCheck() {
        if (!jTxfAmount.getText().equals("") && 
                !jTxfPeople.getText().equals("")) {
            jBtnCalc.setEnabled(true);
        }
        else {
            jBtnCalc.setEnabled(false);
        }
    }
    
    private void reset() {
        jTxfAmount.setText("");
        jTxfPeople.setText("");
        jTxfTipPercent.setText("15%");
        jSldRange.setValue(15);
        jBtnCalc.setEnabled(false);
        jTxfTip.setText("");
        jTxfTotal.setText("");
        jTxfTotalDiner.setText("");
    }
    
    private void displayMessage(String msg) {
        JOptionPane.showMessageDialog(null, msg, "Invalid input", 
                JOptionPane.WARNING_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCalc;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JLabel jLblAmount;
    private javax.swing.JLabel jLblPeople;
    private javax.swing.JLabel jLblTip;
    private javax.swing.JLabel jLblTipAmount;
    private javax.swing.JLabel jLblTipScale;
    private javax.swing.JLabel jLblTitle;
    private javax.swing.JLabel jLblTotal;
    private javax.swing.JLabel jLblTotalDiner;
    private javax.swing.JSlider jSldRange;
    private javax.swing.JTextField jTxfAmount;
    private javax.swing.JTextField jTxfPeople;
    private javax.swing.JTextField jTxfTip;
    private javax.swing.JTextField jTxfTipPercent;
    private javax.swing.JTextField jTxfTotal;
    private javax.swing.JTextField jTxfTotalDiner;
    // End of variables declaration//GEN-END:variables
}
